import type { HeroPatternLanguage } from './hero-exploration-types';

export const HERO_PATTERN_LANGUAGE: readonly HeroPatternLanguage[] = [
  {
    patternKey: 'forceful_driver',
    headline: 'You take hold of momentum quickly.',
    subheadline: 'Direct, fast-moving, and willing to force clarity when the room is drifting.',
    summary: 'This pattern wins when pace, direction, and visible forward motion outweigh the need to hold space for slower alignment.',
    narrative: 'You are likely to read ambiguity as a cue to step in, sharpen the agenda, and make progress tangible. Others may experience you as energising when movement is needed and intense when the context would benefit from more room or patience.',
    pressureOverlay: 'Under pressure, this pattern often becomes firmer, faster, and less tolerant of delay or indecision.',
    environmentOverlay: 'You are usually best placed in environments that reward ownership, urgency, and direct accountability.',
  },
  {
    patternKey: 'structured_collaborator',
    headline: 'You bring order without losing people.',
    subheadline: 'Clear-thinking and inclusive, with a bias toward coordinated execution.',
    summary: 'This pattern wins when structure and people-readability rise together strongly enough to make you look both organised and easy to work with.',
    narrative: 'You are likely to create clarity by connecting plans, expectations, and working relationships instead of treating them as separate problems. The strength is coordinated follow-through; the risk is spending too long trying to keep everyone aligned before committing fully.',
    pressureOverlay: 'Under pressure, you may tighten process while working hard to keep communication constructive and workable.',
    environmentOverlay: 'You tend to do well where dependable structure and collaborative norms are both taken seriously.',
  },
  {
    patternKey: 'exacting_controller',
    headline: 'You raise the standard when conditions get loose.',
    subheadline: 'Precise, corrective, and unwilling to let weak execution pass unnoticed.',
    summary: 'This pattern wins when accuracy, scrutiny, and directional force combine into a highly demanding but stabilising presence.',
    narrative: 'You are likely to spot flaws quickly and respond by narrowing ambiguity, tightening expectations, and making quality visible. At your best this protects standards; overused, it can make the room feel more judged than helped.',
    pressureOverlay: 'Pressure usually sharpens this pattern further, turning concern into corrective intensity and lower tolerance for loose thinking.',
    environmentOverlay: 'You are often strongest in contexts that genuinely need quality control, disciplined reasoning, and clear performance edges.',
  },
  {
    patternKey: 'adaptive_catalyst',
    headline: 'You keep moving by changing shape quickly.',
    subheadline: 'Responsive, experimental, and more comfortable with movement than with fixed form.',
    summary: 'This pattern wins when flexibility and adaptation stay high enough across domains to make reinvention a visible strength.',
    narrative: 'You are likely to make progress by trying angles, reading shifts early, and staying in motion while others are still settling on one route. That makes you useful in changing conditions, though it can frustrate people who need firmer structure before they trust the direction.',
    pressureOverlay: 'Under pressure, you may keep scanning and reconfiguring rather than locking into a single rigid line too early.',
    environmentOverlay: 'You usually fit best where change is normal, initiative is welcome, and adjustment is treated as capability rather than inconsistency.',
  },
  {
    patternKey: 'decisive_orchestrator',
    headline: 'You organise action around clear expectations.',
    subheadline: 'Structured, directive, and comfortable translating ambiguity into execution rules.',
    summary: 'This pattern wins when task direction, order, and visible authority combine into a coherent organising centre.',
    narrative: 'You are likely to create traction by defining what matters, who owns it, and how progress will be judged. The upside is clarity and pace with control; the downside is that others may feel there is less room to influence the route once you have set it.',
    pressureOverlay: 'Pressure often increases your need to simplify decisions, assign ownership clearly, and keep the operating rhythm tight.',
    environmentOverlay: 'You are commonly strongest where accountability, operating discipline, and execution cadence need to stay visible.',
  },
  {
    patternKey: 'relational_catalyst',
    headline: 'You move people by creating energy around the work.',
    subheadline: 'Visible, connective, and able to create momentum through engagement rather than force alone.',
    summary: 'This pattern wins when people focus and pace rise together strongly enough to make your impact feel social as well as directional.',
    narrative: 'You are likely to build progress by keeping people engaged, making the work feel alive, and pulling others into movement early. The benefit is momentum with connection; the risk is that pace and positivity can outrun the harder edges of detail or follow-through.',
    pressureOverlay: 'Under pressure, you may work even harder to keep others connected, motivated, and moving rather than letting the room flatten out.',
    environmentOverlay: 'You usually do best where visibility, collaboration, and momentum-building are valued as real levers of performance.',
  },
  {
    patternKey: 'diplomatic_stabiliser',
    headline: 'You calm the system without disappearing inside it.',
    subheadline: 'Steady, receptive, and good at keeping relationships workable while the ground shifts.',
    summary: 'This pattern wins when steadiness, listening, and social sensitivity create a reliably containing presence.',
    narrative: 'You are likely to reduce unnecessary friction by reading what others need, lowering the emotional temperature, and protecting continuity where possible. The strength is trust and steadiness; the risk is carrying too much relational load before making the harder call.',
    pressureOverlay: 'Pressure often increases your instinct to create safety, reduce escalation, and hold a workable rhythm for others.',
    environmentOverlay: 'You are often strongest where stable collaboration, trust, and measured change are more useful than dramatic resets.',
  },
  {
    patternKey: 'deliberate_craftsperson',
    headline: 'You build confidence through care and precision.',
    subheadline: 'Methodical, quality-driven, and more interested in robustness than rush.',
    summary: 'This pattern wins when deliberation, structure, and standards combine into a visibly careful way of operating.',
    narrative: 'You are likely to create value by slowing the work down enough to improve quality, judgement, and long-term reliability. Others may lean on you for rigour, while also wishing you would sometimes move before every uncertainty has been reduced.',
    pressureOverlay: 'Under pressure, you may become even more careful about evidence, sequence, and quality thresholds.',
    environmentOverlay: 'You usually fit best where strong standards, craft discipline, and thoughtful execution are respected rather than treated as drag.',
  },
  {
    patternKey: 'flexible_mobiliser',
    headline: 'You keep progress alive by staying open and mobile.',
    subheadline: 'Socially agile and willing to adapt the route to keep people engaged.',
    summary: 'This pattern wins when flexibility and people orientation combine more strongly than structure or force.',
    narrative: 'You are likely to make movement possible by adjusting approach, reading the room, and finding ways to keep others with the work even as conditions evolve. The strength is responsiveness; the risk is that constant adaptation can make your centre harder for others to read.',
    pressureOverlay: 'Pressure may increase your tendency to keep options open and preserve room to manoeuvre rather than closing the system down too early.',
    environmentOverlay: 'You tend to work well in settings that reward collaboration, adaptation, and relationship-sensitive progress.',
  },
  {
    patternKey: 'responsive_mediator',
    headline: 'You absorb tension and turn it into workable movement.',
    subheadline: 'Patient, receptive, and inclined to keep disagreement useful rather than polarised.',
    summary: 'This pattern wins when tolerance, listening, and relational steadiness combine into a low-friction influence style.',
    narrative: 'You are likely to help systems stay functional by hearing what is underneath the conflict and looking for a path people can live with. That makes you valuable in difficult interactions, though the pattern can delay sharper resolution when the context genuinely needs a firmer edge.',
    pressureOverlay: 'Under pressure, you often lean toward de-escalation, reframing, and preserving enough trust for people to stay engaged.',
    environmentOverlay: 'You usually fit best where dialogue, relationship continuity, and practical accommodation are part of getting good work done.',
  },
  {
    patternKey: 'calm_operator',
    headline: 'You create trust by being steady and usable.',
    subheadline: 'Consistent, dependable, and quietly focused on keeping work running cleanly.',
    summary: 'This pattern wins when steadiness, task follow-through, and measured pace outweigh the louder or more dramatic signals.',
    narrative: 'You are likely to create confidence by keeping commitments clear, reducing unnecessary volatility, and sustaining progress without making yourself the centre of the room. The value is reliability; the risk is that others may underestimate how much adaptation or challenge you can bring when needed.',
    pressureOverlay: 'Pressure often pulls you toward containment, routine, and preserving workable continuity over dramatic action.',
    environmentOverlay: 'You are commonly strongest in environments that reward disciplined delivery, role clarity, and dependable execution.',
  },
  {
    patternKey: 'balanced_operator',
    headline: 'You present as broadly balanced rather than sharply polarised.',
    subheadline: 'No single Hero rule dominates, so the profile resolves to a steady central pattern.',
    summary: 'This fallback wins when the profile spreads across several traits without crossing any stronger rule threshold cleanly.',
    narrative: 'You are likely to show usable range across contexts, with behaviour shaped more by the situation than by one consistently dominant Hero signature. That can be an advantage in varied roles, though it also means the profile may need richer supporting sections to feel fully distinctive.',
    pressureOverlay: 'Under pressure, the profile may borrow from several nearby styles rather than defaulting to one obvious response pattern.',
    environmentOverlay: 'You usually fit best in environments that value versatility, role balance, and context-sensitive judgement.',
  },
];

export const HERO_PATTERN_LANGUAGE_LOOKUP = new Map(
  HERO_PATTERN_LANGUAGE.map((entry) => [entry.patternKey, entry] as const),
);
