import type { HeroPatternLanguage } from './hero-exploration-types';

export const HERO_PATTERN_LANGUAGE: readonly HeroPatternLanguage[] = [
  {
    patternKey: 'forceful_driver',
    headline: 'You push momentum into motion quickly.',
    subheadline: 'Fast, assertive, and willing to make the path visible before the room fully settles.',
    summary: 'This pattern fits profiles that combine speed with a strong instinct to take hold of direction.',
    narrative: 'You are likely to read hesitation as a signal to step in, sharpen priorities, and move the work forward decisively. At your best this creates traction quickly; overused, it can make others feel as though they are being pulled rather than brought along.',
    pressureOverlay: 'Under pressure, this pattern usually becomes firmer, faster, and less patient with drift.',
    environmentOverlay: 'You are often strongest where urgency, ownership, and clear forward motion are genuinely valuable.',
  },
  {
    patternKey: 'adaptive_challenger',
    headline: 'You adapt fast without softening your edge.',
    subheadline: 'Quick to reframe, quick to challenge, and comfortable changing route while keeping pressure on progress.',
    summary: 'This pattern fits profiles that blend assertive energy with a strong capacity to pivot under changing conditions.',
    narrative: 'You are likely to spot openings, adjust quickly, and still keep enough intensity to stop the work from losing momentum. That can make you highly useful in live, shifting situations, though others may need more clarity to track where the line has moved.',
    pressureOverlay: 'Pressure often increases both your speed of adaptation and your willingness to push a clearer line.',
    environmentOverlay: 'You usually fit best where change is frequent, action still matters, and ambiguity is not treated as a reason to freeze.',
  },
  {
    patternKey: 'adaptive_catalyst',
    headline: 'You keep progress moving by changing shape quickly.',
    subheadline: 'Responsive, experimental, and more comfortable with movement than fixed form.',
    summary: 'This pattern fits profiles where adaptation and flexibility stand out as the dominant response.',
    narrative: 'You are likely to make progress by trying angles, reading shifts early, and staying mobile while others are still settling on one route. That makes you useful in changing conditions, though it can frustrate people who need firmer structure before they trust the direction.',
    pressureOverlay: 'Under pressure, you may keep scanning and reconfiguring rather than locking into one rigid line too early.',
    environmentOverlay: 'You usually fit best where change is normal, initiative is welcome, and adjustment is treated as capability.',
  },
  {
    patternKey: 'adaptive_orchestrator',
    headline: 'You bring structure to change without losing initiative.',
    subheadline: 'Adaptive but organised, with enough force to keep movement coherent.',
    summary: 'This pattern fits profiles that combine changing-course ability with visible structure and direction.',
    narrative: 'You are likely to stabilise moving situations by creating enough order for action to stay coordinated without making the system rigid. The advantage is agile control; the risk is expecting others to keep up with a plan that is still evolving as you drive it.',
    pressureOverlay: 'Pressure usually sharpens your need to coordinate adaptation rather than leaving the change process loose.',
    environmentOverlay: 'You often do well where teams need both responsiveness and clearer operating discipline at the same time.',
  },
  {
    patternKey: 'adaptive_mobiliser',
    headline: 'You keep movement alive by adapting faster than the context settles.',
    subheadline: 'Mobile, inventive, and comfortable changing shape while others are still deciding how fixed the route should be.',
    summary: 'This consolidated pattern fits profiles where change-readiness, flexibility, and forward movement combine into a recognisable adaptive identity.',
    narrative: 'You are likely to create progress by staying open, re-reading the terrain, and finding a next move before the system becomes rigid. That makes you valuable in live, shifting environments, though the same mobility can make your centre harder for others to predict if you do not signal the through-line clearly.',
    pressureOverlay: 'Under pressure, you often become even more adaptive, scanning for workable openings instead of forcing premature closure.',
    environmentOverlay: 'You usually fit best where change is frequent, experimentation is tolerated, and responsiveness counts as real capability rather than drift.',
  },
  {
    patternKey: 'balanced_operator',
    headline: 'You present as broadly balanced rather than sharply polarised.',
    subheadline: 'No stronger Hero rule dominates, so the profile resolves to a steady central pattern.',
    summary: 'This fallback fits profiles that spread across several traits without crossing a more specific rule cleanly.',
    narrative: 'You are likely to show usable range across contexts, with behaviour shaped more by the situation than by one consistently dominant Hero signature. That can be an advantage in varied roles, though it also means the profile may need richer supporting sections to feel fully distinctive.',
    pressureOverlay: 'Under pressure, the profile may borrow from several nearby styles rather than defaulting to one obvious response.',
    environmentOverlay: 'You usually fit best in environments that value versatility, role balance, and context-sensitive judgement.',
  },
  {
    patternKey: 'calm_operator',
    headline: 'You create trust by being steady and usable.',
    subheadline: 'Consistent, dependable, and quietly focused on keeping work running cleanly.',
    summary: 'This legacy pattern represented stable execution with a low-drama operating rhythm.',
    narrative: 'You were likely to create confidence by keeping commitments clear, reducing unnecessary volatility, and sustaining progress without making yourself the centre of the room.',
    pressureOverlay: 'Pressure often pulled this pattern toward containment, routine, and preserving continuity.',
    environmentOverlay: 'It fit environments that rewarded disciplined delivery, role clarity, and dependable execution.',
  },
  {
    patternKey: 'decisive_orchestrator',
    headline: 'You organise action around clear expectations.',
    subheadline: 'Structured, directive, and comfortable translating ambiguity into execution rules.',
    summary: 'This pattern fits profiles where order, task direction, and authority combine into a coherent organising centre.',
    narrative: 'You are likely to create traction by defining what matters, who owns it, and how progress will be judged. The upside is clarity and pace with control; the downside is that others may feel there is less room to influence the route once you have set it.',
    pressureOverlay: 'Pressure often increases your need to simplify decisions, assign ownership clearly, and keep the operating rhythm tight.',
    environmentOverlay: 'You are commonly strongest where accountability, operating discipline, and execution cadence need to stay visible.',
  },
  {
    patternKey: 'deliberate_craftsperson',
    headline: 'You build confidence through care and precision.',
    subheadline: 'Methodical, quality-conscious, and more interested in robustness than rush.',
    summary: 'This pattern fits profiles that slow the work down enough to improve quality, judgement, and long-term reliability.',
    narrative: 'You are likely to create value by checking sequence, improving logic, and making sure the work stands up after the first pass. Others may lean on you for rigour while also wishing you would sometimes move before every uncertainty has been reduced.',
    pressureOverlay: 'Under pressure, you may become even more careful about evidence, sequence, and quality thresholds.',
    environmentOverlay: 'You usually fit best where strong standards, craft discipline, and thoughtful execution are respected rather than treated as drag.',
  },
  {
    patternKey: 'delivery_commander',
    headline: 'You turn direction into visible execution pressure.',
    subheadline: 'Task-led, forceful, and inclined to push delivery before momentum fades.',
    summary: 'This pattern fits profiles that combine a strong delivery bias with enough assertive drive to keep others moving.',
    narrative: 'You are likely to create progress by making ownership visible, raising the bar on follow-through, and keeping the work close to action. That can be highly effective when outcomes matter quickly, though it can feel abrupt if others need more consultation before they commit.',
    pressureOverlay: 'Pressure often makes this pattern more direct, more outcome-focused, and less tolerant of drift.',
    environmentOverlay: 'You usually do best where delivery discipline and visible accountability are treated as core to performance.',
  },
  {
    patternKey: 'diplomatic_stabiliser',
    headline: 'You calm the system without disappearing inside it.',
    subheadline: 'Steady, receptive, and good at keeping relationships workable while the ground shifts.',
    summary: 'This pattern fits profiles where steadiness and social sensitivity create a containing presence.',
    narrative: 'You are likely to reduce unnecessary friction by reading what others need, lowering the emotional temperature, and protecting continuity where possible. The strength is trust and steadiness; the risk is carrying too much relational load before making the harder call.',
    pressureOverlay: 'Pressure often increases your instinct to create safety, reduce escalation, and hold a workable rhythm for others.',
    environmentOverlay: 'You are often strongest where stable collaboration, trust, and measured change are more useful than dramatic resets.',
  },
  {
    patternKey: 'driving_integrator',
    headline: 'You create pace that still keeps people connected.',
    subheadline: 'Fast-moving and socially aware, with momentum built through inclusion rather than force alone.',
    summary: 'This pattern fits profiles where pace and people focus rise together strongly enough to feel both energising and connective.',
    narrative: 'You are likely to move the work forward while still keeping others in the picture, making urgency feel shared rather than purely imposed. The advantage is energetic coordination; the risk is expecting momentum itself to solve problems that still need sharper structure.',
    pressureOverlay: 'Under pressure, you may push for movement while working hard to keep alignment and morale from collapsing.',
    environmentOverlay: 'You tend to work well where high momentum still depends on people staying connected to the direction.',
  },
  {
    patternKey: 'exacting_controller',
    headline: 'You raise the standard when conditions get loose.',
    subheadline: 'Precise, corrective, and unwilling to let weak execution pass unnoticed.',
    summary: 'This pattern fits profiles where accuracy, scrutiny, and directional force combine into a highly demanding presence.',
    narrative: 'You are likely to spot flaws quickly and respond by narrowing ambiguity, tightening expectations, and making quality visible. At your best this protects standards; overused, it can make the room feel more judged than helped.',
    pressureOverlay: 'Pressure usually sharpens this pattern further, turning concern into corrective intensity and lower tolerance for loose thinking.',
    environmentOverlay: 'You are often strongest in contexts that genuinely need quality control, disciplined reasoning, and clear performance edges.',
  },
  {
    patternKey: 'flexible_mobiliser',
    headline: 'You keep progress alive by staying open and mobile.',
    subheadline: 'Socially agile and willing to adapt the route to keep people engaged.',
    summary: 'This pattern fits profiles where flexibility and people orientation combine more strongly than structure or force.',
    narrative: 'You are likely to make movement possible by adjusting approach, reading the room, and finding ways to keep others with the work even as conditions evolve. The strength is responsiveness; the risk is that constant adaptation can make your centre harder for others to read.',
    pressureOverlay: 'Pressure may increase your tendency to keep options open and preserve room to manoeuvre rather than closing the system down too early.',
    environmentOverlay: 'You tend to work well in settings that reward collaboration, adaptation, and relationship-sensitive progress.',
  },
  {
    patternKey: 'grounded_planner',
    headline: 'You create steadiness through thoughtful sequencing.',
    subheadline: 'Measured, dependable, and inclined to make the work safer by planning it properly.',
    summary: 'This pattern fits profiles where deliberation and stability rise together into a calm planning centre.',
    narrative: 'You are likely to protect outcomes by thinking ahead, reducing avoidable volatility, and building enough certainty for others to trust the route. The strength is dependable judgement; the risk is holding the system in planning mode longer than the moment requires.',
    pressureOverlay: 'Under pressure, you may double down on sequence, pacing, and reducing avoidable disruption.',
    environmentOverlay: 'You usually fit best where continuity, preparation, and considered delivery are all taken seriously.',
  },
  {
    patternKey: 'grounded_steward',
    headline: 'You hold people and standards together steadily.',
    subheadline: 'Relationally aware, deliberate, and protective of continuity rather than drama.',
    summary: 'This pattern fits profiles where people care, steadiness, and careful judgement combine into a stewardship style.',
    narrative: 'You are likely to create trust by being thoughtful, dependable, and socially aware without becoming reactive. That gives you a strong holding quality, though others may sometimes need a clearer signal about when you will stop containing and start deciding.',
    pressureOverlay: 'Pressure often strengthens your instinct to stay composed, protect continuity, and keep others anchored.',
    environmentOverlay: 'You often work well where calm stewardship, trust, and measured judgement matter more than theatrical leadership.',
  },
  {
    patternKey: 'relational_catalyst',
    headline: 'You move people by creating energy around the work.',
    subheadline: 'Visible, connective, and able to create momentum through engagement rather than force alone.',
    summary: 'This pattern fits profiles where people focus and pace rise together strongly enough to make your impact feel social as well as directional.',
    narrative: 'You are likely to build progress by keeping people engaged, making the work feel alive, and pulling others into movement early. The benefit is momentum with connection; the risk is that pace and positivity can outrun the harder edges of detail or follow-through.',
    pressureOverlay: 'Under pressure, you may work even harder to keep others connected, motivated, and moving rather than letting the room flatten out.',
    environmentOverlay: 'You usually do best where visibility, collaboration, and momentum-building are valued as real levers of performance.',
  },
  {
    patternKey: 'responsive_mediator',
    headline: 'You absorb tension and turn it into workable movement.',
    subheadline: 'Patient, receptive, and inclined to keep disagreement useful rather than polarised.',
    summary: 'This pattern fits profiles where listening, tolerance, and social steadiness combine into low-friction influence.',
    narrative: 'You are likely to help systems stay functional by hearing what sits underneath the conflict and looking for a path people can live with. That makes you valuable in difficult interactions, though the pattern can delay sharper resolution when the context genuinely needs a firmer edge.',
    pressureOverlay: 'Under pressure, you often lean toward de-escalation, reframing, and preserving enough trust for people to stay engaged.',
    environmentOverlay: 'You usually fit best where dialogue, relationship continuity, and practical accommodation are part of getting good work done.',
  },
  {
    patternKey: 'steady_connector',
    headline: 'You keep people coordinated by being reliably present.',
    subheadline: 'Socially steady, quietly containing, and more interested in keeping the system workable than dramatic.',
    summary: 'This pattern fits profiles where people focus and stability combine into a dependable connective role.',
    narrative: 'You are likely to create cohesion by staying usable, reducing unnecessary churn, and helping others feel the work is still manageable. The strength is reliable connection; the risk is staying in support mode when the context needs a stronger pivot or firmer challenge.',
    pressureOverlay: 'Pressure may increase your instinct to create steadiness for others and prevent the system from becoming fragmented.',
    environmentOverlay: 'You often do well in environments that value trust, continuity, and socially reliable coordination.',
  },
  {
    patternKey: 'steady_steward',
    headline: 'You create trust by holding people and continuity together.',
    subheadline: 'Calm, people-aware, and more interested in keeping the system workable than making yourself dramatic inside it.',
    summary: 'This consolidated pattern fits profiles where social awareness and stability combine into a clear stewardship identity.',
    narrative: 'You are likely to create confidence by staying usable, reading what others need, and keeping enough continuity for the work to remain coherent through friction or change. The strength is steady containment; the risk is carrying the relational load longer than the moment really requires before naming the harder decision.',
    pressureOverlay: 'Under pressure, you often move further toward containment, reassurance, and keeping the room workable enough to continue.',
    environmentOverlay: 'You usually work best where trust, continuity, and relationship-sensitive judgement are treated as central to performance rather than secondary to louder forms of leadership.',
  },
  {
    patternKey: 'steady_executor',
    headline: 'You create confidence through steady delivery.',
    subheadline: 'Reliable, task-led, and inclined to keep the work moving without unnecessary noise.',
    summary: 'This pattern fits profiles where task ownership and steadiness rise together into a delivery-first presence.',
    narrative: 'You are likely to add value by making progress dependable, keeping commitments visible, and reducing the chances that momentum breaks down through inconsistency. That can make you highly trusted, though others may sometimes want more visible stretch or experimentation from you.',
    pressureOverlay: 'Under pressure, you often narrow toward reliable follow-through and protecting what still needs to get done.',
    environmentOverlay: 'You usually fit best where dependable execution and low-drama ownership are more useful than constant reinvention.',
  },
  {
    patternKey: 'structured_collaborator',
    headline: 'You bring order without losing people.',
    subheadline: 'Clear-thinking and inclusive, with a bias toward coordinated execution.',
    summary: 'This pattern fits profiles where structure and people-readability rise together strongly enough to make you look both organised and easy to work with.',
    narrative: 'You are likely to create clarity by connecting plans, expectations, and working relationships instead of treating them as separate problems. The strength is coordinated follow-through; the risk is spending too long trying to keep everyone aligned before committing fully.',
    pressureOverlay: 'Under pressure, you may tighten process while working hard to keep communication constructive and workable.',
    environmentOverlay: 'You tend to do well where dependable structure and collaborative norms are both taken seriously.',
  },
  {
    patternKey: 'structured_operator',
    headline: 'You make delivery predictable by organising it well.',
    subheadline: 'Structured, task-focused, and inclined to stabilise work through clear operating discipline.',
    summary: 'This pattern fits profiles where order and task ownership combine more strongly than pace or visibility.',
    narrative: 'You are likely to improve outcomes by clarifying method, tightening follow-through, and making the work easier to trust because it is easier to track. The strength is operational dependability; the risk is becoming slower to adjust when the context no longer fits the structure you have built.',
    pressureOverlay: 'Under pressure, you may move toward even clearer roles, stronger process, and tighter execution control.',
    environmentOverlay: 'You usually work well where consistency, structure, and disciplined delivery matter more than improvisation.',
  },
];

export const HERO_PATTERN_LANGUAGE_LOOKUP = new Map(
  HERO_PATTERN_LANGUAGE.map((entry) => [entry.patternKey, entry] as const),
);
